# Generated by Django 4.1.5 on 2023-02-03 19:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("driver_status", models.BooleanField()),
                ("type", models.CharField(max_length=200, null=True)),
                ("plate", models.CharField(max_length=200, null=True)),
                ("passengers_num", models.IntegerField(null=True)),
                ("special_vehicle_info", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                (
                    "arrival_time",
                    models.DateTimeField(verbose_name="Arrival date & time"),
                ),
                ("shared_status", models.BooleanField(default=False)),
                ("owner_num", models.IntegerField()),
                ("passenger_num", models.IntegerField()),
                (
                    "sharer_num",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(), size=None
                        ),
                        default=[[]],
                        size=None,
                    ),
                ),
                (
                    "sharer_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        default=[],
                        size=None,
                    ),
                ),
                ("ride_status", models.CharField(default="open", max_length=200)),
                ("driver_name", models.CharField(max_length=200, null=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=200)),
                ("special_request", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshareapp.userinfo",
                    ),
                ),
            ],
        ),
    ]
