# Generated by Django 4.1.5 on 2023-02-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rideshareapp", "0002_alter_ride_sharer_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="sharer_num",
        ),
    ]
