# Generated by Django 4.1.5 on 2023-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideshareapp", "0004_ride_sharer_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
